//COLORS
export const Colors = {
  COMPANY: {
    PRIMARY: "#375484",
    PRIMARY_DARK: "#1C355E",
    PRIMARY_DISABLED: "#37548420",

    SECONDARY: "#FFF",
    SECONDARY_DARK: "#1C355E10",
    SECONDARY_DISABLED: "#FFF",

    PRIMARY_DISABLED: "#1C355E10"

  },
  APP: {
    LIGHT_GRAY: "#F5F5F5",
    DARK_GRAY: "#393737",
    PLACEHOLDER_LIGHT_GRAY: "#BFBFBF",
  },
  PIN: {
    ALL_AVAILABLE: "#2EB85E",
    SOME_AVAILABLE: "#3DAAFA",
    NONE_AVAILABLE: "#FAA220",
    UNAVAILABLE: "#FA5852",
  },
};
export const texts = {
  COMPANY: {
    WELCOME: "Hola",
  },
};
